project:
  type: website
  output-dir: .

website:
  title: "ad688-employability-sp25A1-group3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data_analysis.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "Multiple Linear Regression"
      - href: unsupervised_learning.qmd
        text: "Unsupervised Learning"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: true
  eval: true
  code-fold: true
