project:
  type: website
  output-dir: .

website:
  title: "ad688-employability-sp25A1-group3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
