project:
  type: website
  output-dir: .

website:
  title: "ad688-employability-sp25A1-group3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data_analysis.qmd
        text: "Exploratory Data Analysis"
      - href: data_cleaning.qmd/ipynb
        text: "Data Cleaning & Exploration"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd/ipynb
        text: "ML Methods"
      - href: nlp_methods.qmd/ipynb
        text: "NLP Methods"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: true
  eval: false
  code-fold: true
